### ISSUE TITLE
There are no bugs here😋

### ISSUE THREAD

**Issue by ltxhhz** [welefen/canvas2video#4]
模块好得很没有bug

我下载的模块是这样
![image](https://user-images.githubusercontent.com/51697596/108627949-081c0280-7493-11eb-82c6-e533363eef65.png)

你可以把这个
![image](https://user-images.githubusercontent.com/51697596/108627794-5381e100-7492-11eb-8aa1-1e1aa3c7ade3.png)
换成这样吗
![image](https://user-images.githubusercontent.com/51697596/108627855-993ea980-7492-11eb-919e-f2383ddcebfa.png)

不然只能这样才能引用成功
![image](https://user-images.githubusercontent.com/51697596/108627845-8fb54180-7492-11eb-945c-26163e61abe2.png)
我不知道是不是我的问题。。

**Comment by ltxhhz** [comment]
希望您能继续更新不要弃坑😗

**Comment by welefen** [comment]
dist 里是 webpack 打包后的代码了

**Comment by welefen** [comment]
1.1.4 版本增加了 lib 目录了，并且也修改了 main 字段指向

**Comment by ltxhhz** [comment]
> 1.1.4 版本增加了 lib 目录了，并且也修改了 main 字段指向

👻还好没弃坑，i了i了

**Comment by welefen** [comment]
@ltxhhz  为啥你有这么大的弃坑疑虑呢

**Comment by ltxhhz** [comment]
就是怕出问题了没得用了，又懒得自己写，而且类似的模块好像很少
